### ISSUE TITLE
:ensure_not parse error

### ISSUE THREAD

**Issue by Avi-D-coder** [cozodb/cozo#103] opened 2023-05-10 19:51 UTC
Tested in the wasm repl `:ensure_not id_alloc{id}` gives the same error.

```
%ignore_error { :create id_alloc{id: Int => next_id: Int, last_id: Int}}
{
    ?[id, next_id, last_id] <- [[0, 1, 1000]];
    :ensure_not id_alloc{id => next_id, last_id}
}
```

```
parser::pest

  × The query parser has encountered unexpected input / end of input at 138..138
   ╭─[3:1]
 3 │     ?[id, next_id, last_id] <- [[0, 1, 1000]];
 4 │     :ensure_not id_alloc{id => next_id, last_id}
   ·                 ▲
 5 │ }
   ╰────
```

Secondary question would you take PR implementing golden tests with input and out dirs to make testing easier?

**Comment by zh217** [comment] 2023-05-11 01:22
Caused by parser priority. Will be fixed.

**Comment by Avi-D-coder** [comment] 2023-05-11 02:38
@zh217 Would You except a PR setting up golden tests?

**Comment by zh217** [comment] 2023-05-11 02:44
@Avi-D-coder Yes, that would be very welcome. The tests are currently in a mess and should be fixed.

**Comment by zh217** [comment] 2023-05-11 02:49
Actually this has already been fixed by https://github.com/cozodb/cozo/commit/55c27e43966d29b66a1ebad1f3b9fe949af94f6c, but the commit refered to the wrong issue.

**Closed** 2023-06-01 02:56 UTC
Labels: bug
